name: sample-nodejs
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-nodejs
  name: sample-nodejs
  run_command: printenv; yarn start
  envs:
  - key: ALPHASPHERE_RUN_TIME
    scope: RUN_TIME
    value: "ALPHASPHERE_RUN_TIME"
    type: GENERAL
  - key: ALPHASPHERE_BUILD_TIME
    scope: BUILD_TIME
    value: ALPHASPHERE_BUILD_TIME
    type: GENERAL
  - key: ALPHASPHERE_RUN_AND_BUILD_TIME
    scope: RUN_AND_BUILD_TIME
    value: ALPHASPHERE_RUN_AND_BUILD_TIME
    type: GENERAL